// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login_enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_login_5fenum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_login_5fenum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_login_5fenum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_login_5fenum_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_login_5fenum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum kLoginMessage : int {
  kOk = 0,
  kIdInvalid = 1,
  kPwInvlid = 2,
  kAlreadyConnected = 3,
  kLoginMessage_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  kLoginMessage_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool kLoginMessage_IsValid(int value);
constexpr kLoginMessage kLoginMessage_MIN = kOk;
constexpr kLoginMessage kLoginMessage_MAX = kAlreadyConnected;
constexpr int kLoginMessage_ARRAYSIZE = kLoginMessage_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* kLoginMessage_descriptor();
template<typename T>
inline const std::string& kLoginMessage_Name(T enum_t_value) {
  static_assert(::std::is_same<T, kLoginMessage>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function kLoginMessage_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    kLoginMessage_descriptor(), enum_t_value);
}
inline bool kLoginMessage_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, kLoginMessage* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<kLoginMessage>(
    kLoginMessage_descriptor(), name, value);
}
enum kCreateMessage : int {
  kCreateSuccess = 0,
  kDuplication = 1,
  kCreateMessage_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  kCreateMessage_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool kCreateMessage_IsValid(int value);
constexpr kCreateMessage kCreateMessage_MIN = kCreateSuccess;
constexpr kCreateMessage kCreateMessage_MAX = kDuplication;
constexpr int kCreateMessage_ARRAYSIZE = kCreateMessage_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* kCreateMessage_descriptor();
template<typename T>
inline const std::string& kCreateMessage_Name(T enum_t_value) {
  static_assert(::std::is_same<T, kCreateMessage>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function kCreateMessage_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    kCreateMessage_descriptor(), enum_t_value);
}
inline bool kCreateMessage_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, kCreateMessage* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<kCreateMessage>(
    kCreateMessage_descriptor(), name, value);
}
enum kCharacterSelectMessage : int {
  kSelectSuccess = 0,
  kSelectFailed = 1,
  kCharacterSelectMessage_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  kCharacterSelectMessage_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool kCharacterSelectMessage_IsValid(int value);
constexpr kCharacterSelectMessage kCharacterSelectMessage_MIN = kSelectSuccess;
constexpr kCharacterSelectMessage kCharacterSelectMessage_MAX = kSelectFailed;
constexpr int kCharacterSelectMessage_ARRAYSIZE = kCharacterSelectMessage_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* kCharacterSelectMessage_descriptor();
template<typename T>
inline const std::string& kCharacterSelectMessage_Name(T enum_t_value) {
  static_assert(::std::is_same<T, kCharacterSelectMessage>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function kCharacterSelectMessage_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    kCharacterSelectMessage_descriptor(), enum_t_value);
}
inline bool kCharacterSelectMessage_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, kCharacterSelectMessage* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<kCharacterSelectMessage>(
    kCharacterSelectMessage_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::kLoginMessage> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::kLoginMessage>() {
  return ::Protocol::kLoginMessage_descriptor();
}
template <> struct is_proto_enum< ::Protocol::kCreateMessage> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::kCreateMessage>() {
  return ::Protocol::kCreateMessage_descriptor();
}
template <> struct is_proto_enum< ::Protocol::kCharacterSelectMessage> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::kCharacterSelectMessage>() {
  return ::Protocol::kCharacterSelectMessage_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_login_5fenum_2eproto
