// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "enum.pb.h"
#include "struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protocol_2eproto;
namespace Protocol {
class ClientCharacterList;
struct ClientCharacterListDefaultTypeInternal;
extern ClientCharacterListDefaultTypeInternal _ClientCharacterList_default_instance_;
class ClientCreateCharacter;
struct ClientCreateCharacterDefaultTypeInternal;
extern ClientCreateCharacterDefaultTypeInternal _ClientCreateCharacter_default_instance_;
class ClientLogin;
struct ClientLoginDefaultTypeInternal;
extern ClientLoginDefaultTypeInternal _ClientLogin_default_instance_;
class ServerCharacterList;
struct ServerCharacterListDefaultTypeInternal;
extern ServerCharacterListDefaultTypeInternal _ServerCharacterList_default_instance_;
class ServerCreateCharacter;
struct ServerCreateCharacterDefaultTypeInternal;
extern ServerCreateCharacterDefaultTypeInternal _ServerCreateCharacter_default_instance_;
class ServerLogin;
struct ServerLoginDefaultTypeInternal;
extern ServerLoginDefaultTypeInternal _ServerLogin_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::ClientCharacterList* Arena::CreateMaybeMessage<::Protocol::ClientCharacterList>(Arena*);
template<> ::Protocol::ClientCreateCharacter* Arena::CreateMaybeMessage<::Protocol::ClientCreateCharacter>(Arena*);
template<> ::Protocol::ClientLogin* Arena::CreateMaybeMessage<::Protocol::ClientLogin>(Arena*);
template<> ::Protocol::ServerCharacterList* Arena::CreateMaybeMessage<::Protocol::ServerCharacterList>(Arena*);
template<> ::Protocol::ServerCreateCharacter* Arena::CreateMaybeMessage<::Protocol::ServerCreateCharacter>(Arena*);
template<> ::Protocol::ServerLogin* Arena::CreateMaybeMessage<::Protocol::ServerLogin>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class ClientLogin final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ClientLogin) */ {
 public:
  inline ClientLogin() : ClientLogin(nullptr) {}
  ~ClientLogin() override;
  explicit constexpr ClientLogin(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientLogin(const ClientLogin& from);
  ClientLogin(ClientLogin&& from) noexcept
    : ClientLogin() {
    *this = ::std::move(from);
  }

  inline ClientLogin& operator=(const ClientLogin& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientLogin& operator=(ClientLogin&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientLogin& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClientLogin* internal_default_instance() {
    return reinterpret_cast<const ClientLogin*>(
               &_ClientLogin_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClientLogin& a, ClientLogin& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientLogin* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientLogin* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ClientLogin* New() const final {
    return new ClientLogin();
  }

  ClientLogin* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ClientLogin>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ClientLogin& from);
  void MergeFrom(const ClientLogin& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientLogin* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ClientLogin";
  }
  protected:
  explicit ClientLogin(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kPwFieldNumber = 2,
    kAuthFieldNumber = 3,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string pw = 2;
  void clear_pw();
  const std::string& pw() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pw(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pw();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_pw();
  void set_allocated_pw(std::string* pw);
  private:
  const std::string& _internal_pw() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pw(const std::string& value);
  std::string* _internal_mutable_pw();
  public:

  // string auth = 3;
  void clear_auth();
  const std::string& auth() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_auth(ArgT0&& arg0, ArgT... args);
  std::string* mutable_auth();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_auth();
  void set_allocated_auth(std::string* auth);
  private:
  const std::string& _internal_auth() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_auth(const std::string& value);
  std::string* _internal_mutable_auth();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ClientLogin)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pw_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr auth_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2eproto;
};
// -------------------------------------------------------------------

class ServerLogin final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ServerLogin) */ {
 public:
  inline ServerLogin() : ServerLogin(nullptr) {}
  ~ServerLogin() override;
  explicit constexpr ServerLogin(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerLogin(const ServerLogin& from);
  ServerLogin(ServerLogin&& from) noexcept
    : ServerLogin() {
    *this = ::std::move(from);
  }

  inline ServerLogin& operator=(const ServerLogin& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerLogin& operator=(ServerLogin&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServerLogin& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerLogin* internal_default_instance() {
    return reinterpret_cast<const ServerLogin*>(
               &_ServerLogin_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ServerLogin& a, ServerLogin& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerLogin* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerLogin* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServerLogin* New() const final {
    return new ServerLogin();
  }

  ServerLogin* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServerLogin>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ServerLogin& from);
  void MergeFrom(const ServerLogin& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerLogin* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ServerLogin";
  }
  protected:
  explicit ServerLogin(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // .Protocol.kLoginMessage result = 1;
  void clear_result();
  ::Protocol::kLoginMessage result() const;
  void set_result(::Protocol::kLoginMessage value);
  private:
  ::Protocol::kLoginMessage _internal_result() const;
  void _internal_set_result(::Protocol::kLoginMessage value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ServerLogin)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2eproto;
};
// -------------------------------------------------------------------

class ClientCharacterList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ClientCharacterList) */ {
 public:
  inline ClientCharacterList() : ClientCharacterList(nullptr) {}
  ~ClientCharacterList() override;
  explicit constexpr ClientCharacterList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientCharacterList(const ClientCharacterList& from);
  ClientCharacterList(ClientCharacterList&& from) noexcept
    : ClientCharacterList() {
    *this = ::std::move(from);
  }

  inline ClientCharacterList& operator=(const ClientCharacterList& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientCharacterList& operator=(ClientCharacterList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientCharacterList& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClientCharacterList* internal_default_instance() {
    return reinterpret_cast<const ClientCharacterList*>(
               &_ClientCharacterList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ClientCharacterList& a, ClientCharacterList& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientCharacterList* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientCharacterList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ClientCharacterList* New() const final {
    return new ClientCharacterList();
  }

  ClientCharacterList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ClientCharacterList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ClientCharacterList& from);
  void MergeFrom(const ClientCharacterList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientCharacterList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ClientCharacterList";
  }
  protected:
  explicit ClientCharacterList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Protocol.ClientCharacterList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2eproto;
};
// -------------------------------------------------------------------

class ServerCharacterList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ServerCharacterList) */ {
 public:
  inline ServerCharacterList() : ServerCharacterList(nullptr) {}
  ~ServerCharacterList() override;
  explicit constexpr ServerCharacterList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerCharacterList(const ServerCharacterList& from);
  ServerCharacterList(ServerCharacterList&& from) noexcept
    : ServerCharacterList() {
    *this = ::std::move(from);
  }

  inline ServerCharacterList& operator=(const ServerCharacterList& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerCharacterList& operator=(ServerCharacterList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServerCharacterList& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerCharacterList* internal_default_instance() {
    return reinterpret_cast<const ServerCharacterList*>(
               &_ServerCharacterList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ServerCharacterList& a, ServerCharacterList& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerCharacterList* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerCharacterList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServerCharacterList* New() const final {
    return new ServerCharacterList();
  }

  ServerCharacterList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServerCharacterList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ServerCharacterList& from);
  void MergeFrom(const ServerCharacterList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerCharacterList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ServerCharacterList";
  }
  protected:
  explicit ServerCharacterList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCharactersFieldNumber = 1,
  };
  // repeated .Protocol.ViewCharacter characters = 1;
  int characters_size() const;
  private:
  int _internal_characters_size() const;
  public:
  void clear_characters();
  ::Protocol::ViewCharacter* mutable_characters(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ViewCharacter >*
      mutable_characters();
  private:
  const ::Protocol::ViewCharacter& _internal_characters(int index) const;
  ::Protocol::ViewCharacter* _internal_add_characters();
  public:
  const ::Protocol::ViewCharacter& characters(int index) const;
  ::Protocol::ViewCharacter* add_characters();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ViewCharacter >&
      characters() const;

  // @@protoc_insertion_point(class_scope:Protocol.ServerCharacterList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ViewCharacter > characters_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2eproto;
};
// -------------------------------------------------------------------

class ClientCreateCharacter final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ClientCreateCharacter) */ {
 public:
  inline ClientCreateCharacter() : ClientCreateCharacter(nullptr) {}
  ~ClientCreateCharacter() override;
  explicit constexpr ClientCreateCharacter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientCreateCharacter(const ClientCreateCharacter& from);
  ClientCreateCharacter(ClientCreateCharacter&& from) noexcept
    : ClientCreateCharacter() {
    *this = ::std::move(from);
  }

  inline ClientCreateCharacter& operator=(const ClientCreateCharacter& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientCreateCharacter& operator=(ClientCreateCharacter&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientCreateCharacter& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClientCreateCharacter* internal_default_instance() {
    return reinterpret_cast<const ClientCreateCharacter*>(
               &_ClientCreateCharacter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ClientCreateCharacter& a, ClientCreateCharacter& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientCreateCharacter* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientCreateCharacter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ClientCreateCharacter* New() const final {
    return new ClientCreateCharacter();
  }

  ClientCreateCharacter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ClientCreateCharacter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ClientCreateCharacter& from);
  void MergeFrom(const ClientCreateCharacter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientCreateCharacter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ClientCreateCharacter";
  }
  protected:
  explicit ClientCreateCharacter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kGenderFieldNumber = 2,
    kCoatIndexFieldNumber = 3,
    kPantsIndexFieldNumber = 4,
    kFaceIndexFieldNumber = 5,
    kShoesIndexFieldNumber = 6,
  };
  // bytes name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // bool gender = 2;
  void clear_gender();
  bool gender() const;
  void set_gender(bool value);
  private:
  bool _internal_gender() const;
  void _internal_set_gender(bool value);
  public:

  // int32 coatIndex = 3;
  void clear_coatindex();
  ::PROTOBUF_NAMESPACE_ID::int32 coatindex() const;
  void set_coatindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_coatindex() const;
  void _internal_set_coatindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 pantsIndex = 4;
  void clear_pantsindex();
  ::PROTOBUF_NAMESPACE_ID::int32 pantsindex() const;
  void set_pantsindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_pantsindex() const;
  void _internal_set_pantsindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 faceIndex = 5;
  void clear_faceindex();
  ::PROTOBUF_NAMESPACE_ID::int32 faceindex() const;
  void set_faceindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_faceindex() const;
  void _internal_set_faceindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 shoesIndex = 6;
  void clear_shoesindex();
  ::PROTOBUF_NAMESPACE_ID::int32 shoesindex() const;
  void set_shoesindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_shoesindex() const;
  void _internal_set_shoesindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ClientCreateCharacter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  bool gender_;
  ::PROTOBUF_NAMESPACE_ID::int32 coatindex_;
  ::PROTOBUF_NAMESPACE_ID::int32 pantsindex_;
  ::PROTOBUF_NAMESPACE_ID::int32 faceindex_;
  ::PROTOBUF_NAMESPACE_ID::int32 shoesindex_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2eproto;
};
// -------------------------------------------------------------------

class ServerCreateCharacter final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ServerCreateCharacter) */ {
 public:
  inline ServerCreateCharacter() : ServerCreateCharacter(nullptr) {}
  ~ServerCreateCharacter() override;
  explicit constexpr ServerCreateCharacter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerCreateCharacter(const ServerCreateCharacter& from);
  ServerCreateCharacter(ServerCreateCharacter&& from) noexcept
    : ServerCreateCharacter() {
    *this = ::std::move(from);
  }

  inline ServerCreateCharacter& operator=(const ServerCreateCharacter& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerCreateCharacter& operator=(ServerCreateCharacter&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServerCreateCharacter& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerCreateCharacter* internal_default_instance() {
    return reinterpret_cast<const ServerCreateCharacter*>(
               &_ServerCreateCharacter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ServerCreateCharacter& a, ServerCreateCharacter& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerCreateCharacter* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerCreateCharacter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServerCreateCharacter* New() const final {
    return new ServerCreateCharacter();
  }

  ServerCreateCharacter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServerCreateCharacter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ServerCreateCharacter& from);
  void MergeFrom(const ServerCreateCharacter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerCreateCharacter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ServerCreateCharacter";
  }
  protected:
  explicit ServerCreateCharacter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCharacterFieldNumber = 2,
    kResultFieldNumber = 1,
  };
  // .Protocol.ViewCharacter character = 2;
  bool has_character() const;
  private:
  bool _internal_has_character() const;
  public:
  void clear_character();
  const ::Protocol::ViewCharacter& character() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::ViewCharacter* release_character();
  ::Protocol::ViewCharacter* mutable_character();
  void set_allocated_character(::Protocol::ViewCharacter* character);
  private:
  const ::Protocol::ViewCharacter& _internal_character() const;
  ::Protocol::ViewCharacter* _internal_mutable_character();
  public:
  void unsafe_arena_set_allocated_character(
      ::Protocol::ViewCharacter* character);
  ::Protocol::ViewCharacter* unsafe_arena_release_character();

  // .Protocol.kCreateMessage result = 1;
  void clear_result();
  ::Protocol::kCreateMessage result() const;
  void set_result(::Protocol::kCreateMessage value);
  private:
  ::Protocol::kCreateMessage _internal_result() const;
  void _internal_set_result(::Protocol::kCreateMessage value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ServerCreateCharacter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Protocol::ViewCharacter* character_;
  int result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientLogin

// string id = 1;
inline void ClientLogin::clear_id() {
  id_.ClearToEmpty();
}
inline const std::string& ClientLogin::id() const {
  // @@protoc_insertion_point(field_get:Protocol.ClientLogin.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientLogin::set_id(ArgT0&& arg0, ArgT... args) {
 
 id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.ClientLogin.id)
}
inline std::string* ClientLogin::mutable_id() {
  // @@protoc_insertion_point(field_mutable:Protocol.ClientLogin.id)
  return _internal_mutable_id();
}
inline const std::string& ClientLogin::_internal_id() const {
  return id_.Get();
}
inline void ClientLogin::_internal_set_id(const std::string& value) {
  
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ClientLogin::_internal_mutable_id() {
  
  return id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ClientLogin::release_id() {
  // @@protoc_insertion_point(field_release:Protocol.ClientLogin.id)
  return id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ClientLogin::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), id,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Protocol.ClientLogin.id)
}

// string pw = 2;
inline void ClientLogin::clear_pw() {
  pw_.ClearToEmpty();
}
inline const std::string& ClientLogin::pw() const {
  // @@protoc_insertion_point(field_get:Protocol.ClientLogin.pw)
  return _internal_pw();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientLogin::set_pw(ArgT0&& arg0, ArgT... args) {
 
 pw_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.ClientLogin.pw)
}
inline std::string* ClientLogin::mutable_pw() {
  // @@protoc_insertion_point(field_mutable:Protocol.ClientLogin.pw)
  return _internal_mutable_pw();
}
inline const std::string& ClientLogin::_internal_pw() const {
  return pw_.Get();
}
inline void ClientLogin::_internal_set_pw(const std::string& value) {
  
  pw_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ClientLogin::_internal_mutable_pw() {
  
  return pw_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ClientLogin::release_pw() {
  // @@protoc_insertion_point(field_release:Protocol.ClientLogin.pw)
  return pw_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ClientLogin::set_allocated_pw(std::string* pw) {
  if (pw != nullptr) {
    
  } else {
    
  }
  pw_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), pw,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Protocol.ClientLogin.pw)
}

// string auth = 3;
inline void ClientLogin::clear_auth() {
  auth_.ClearToEmpty();
}
inline const std::string& ClientLogin::auth() const {
  // @@protoc_insertion_point(field_get:Protocol.ClientLogin.auth)
  return _internal_auth();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientLogin::set_auth(ArgT0&& arg0, ArgT... args) {
 
 auth_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.ClientLogin.auth)
}
inline std::string* ClientLogin::mutable_auth() {
  // @@protoc_insertion_point(field_mutable:Protocol.ClientLogin.auth)
  return _internal_mutable_auth();
}
inline const std::string& ClientLogin::_internal_auth() const {
  return auth_.Get();
}
inline void ClientLogin::_internal_set_auth(const std::string& value) {
  
  auth_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ClientLogin::_internal_mutable_auth() {
  
  return auth_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ClientLogin::release_auth() {
  // @@protoc_insertion_point(field_release:Protocol.ClientLogin.auth)
  return auth_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ClientLogin::set_allocated_auth(std::string* auth) {
  if (auth != nullptr) {
    
  } else {
    
  }
  auth_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), auth,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Protocol.ClientLogin.auth)
}

// -------------------------------------------------------------------

// ServerLogin

// .Protocol.kLoginMessage result = 1;
inline void ServerLogin::clear_result() {
  result_ = 0;
}
inline ::Protocol::kLoginMessage ServerLogin::_internal_result() const {
  return static_cast< ::Protocol::kLoginMessage >(result_);
}
inline ::Protocol::kLoginMessage ServerLogin::result() const {
  // @@protoc_insertion_point(field_get:Protocol.ServerLogin.result)
  return _internal_result();
}
inline void ServerLogin::_internal_set_result(::Protocol::kLoginMessage value) {
  
  result_ = value;
}
inline void ServerLogin::set_result(::Protocol::kLoginMessage value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:Protocol.ServerLogin.result)
}

// -------------------------------------------------------------------

// ClientCharacterList

// -------------------------------------------------------------------

// ServerCharacterList

// repeated .Protocol.ViewCharacter characters = 1;
inline int ServerCharacterList::_internal_characters_size() const {
  return characters_.size();
}
inline int ServerCharacterList::characters_size() const {
  return _internal_characters_size();
}
inline ::Protocol::ViewCharacter* ServerCharacterList::mutable_characters(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.ServerCharacterList.characters)
  return characters_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ViewCharacter >*
ServerCharacterList::mutable_characters() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.ServerCharacterList.characters)
  return &characters_;
}
inline const ::Protocol::ViewCharacter& ServerCharacterList::_internal_characters(int index) const {
  return characters_.Get(index);
}
inline const ::Protocol::ViewCharacter& ServerCharacterList::characters(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.ServerCharacterList.characters)
  return _internal_characters(index);
}
inline ::Protocol::ViewCharacter* ServerCharacterList::_internal_add_characters() {
  return characters_.Add();
}
inline ::Protocol::ViewCharacter* ServerCharacterList::add_characters() {
  // @@protoc_insertion_point(field_add:Protocol.ServerCharacterList.characters)
  return _internal_add_characters();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ViewCharacter >&
ServerCharacterList::characters() const {
  // @@protoc_insertion_point(field_list:Protocol.ServerCharacterList.characters)
  return characters_;
}

// -------------------------------------------------------------------

// ClientCreateCharacter

// bytes name = 1;
inline void ClientCreateCharacter::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& ClientCreateCharacter::name() const {
  // @@protoc_insertion_point(field_get:Protocol.ClientCreateCharacter.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientCreateCharacter::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.ClientCreateCharacter.name)
}
inline std::string* ClientCreateCharacter::mutable_name() {
  // @@protoc_insertion_point(field_mutable:Protocol.ClientCreateCharacter.name)
  return _internal_mutable_name();
}
inline const std::string& ClientCreateCharacter::_internal_name() const {
  return name_.Get();
}
inline void ClientCreateCharacter::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ClientCreateCharacter::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ClientCreateCharacter::release_name() {
  // @@protoc_insertion_point(field_release:Protocol.ClientCreateCharacter.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ClientCreateCharacter::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Protocol.ClientCreateCharacter.name)
}

// bool gender = 2;
inline void ClientCreateCharacter::clear_gender() {
  gender_ = false;
}
inline bool ClientCreateCharacter::_internal_gender() const {
  return gender_;
}
inline bool ClientCreateCharacter::gender() const {
  // @@protoc_insertion_point(field_get:Protocol.ClientCreateCharacter.gender)
  return _internal_gender();
}
inline void ClientCreateCharacter::_internal_set_gender(bool value) {
  
  gender_ = value;
}
inline void ClientCreateCharacter::set_gender(bool value) {
  _internal_set_gender(value);
  // @@protoc_insertion_point(field_set:Protocol.ClientCreateCharacter.gender)
}

// int32 coatIndex = 3;
inline void ClientCreateCharacter::clear_coatindex() {
  coatindex_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ClientCreateCharacter::_internal_coatindex() const {
  return coatindex_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ClientCreateCharacter::coatindex() const {
  // @@protoc_insertion_point(field_get:Protocol.ClientCreateCharacter.coatIndex)
  return _internal_coatindex();
}
inline void ClientCreateCharacter::_internal_set_coatindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  coatindex_ = value;
}
inline void ClientCreateCharacter::set_coatindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_coatindex(value);
  // @@protoc_insertion_point(field_set:Protocol.ClientCreateCharacter.coatIndex)
}

// int32 pantsIndex = 4;
inline void ClientCreateCharacter::clear_pantsindex() {
  pantsindex_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ClientCreateCharacter::_internal_pantsindex() const {
  return pantsindex_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ClientCreateCharacter::pantsindex() const {
  // @@protoc_insertion_point(field_get:Protocol.ClientCreateCharacter.pantsIndex)
  return _internal_pantsindex();
}
inline void ClientCreateCharacter::_internal_set_pantsindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  pantsindex_ = value;
}
inline void ClientCreateCharacter::set_pantsindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_pantsindex(value);
  // @@protoc_insertion_point(field_set:Protocol.ClientCreateCharacter.pantsIndex)
}

// int32 faceIndex = 5;
inline void ClientCreateCharacter::clear_faceindex() {
  faceindex_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ClientCreateCharacter::_internal_faceindex() const {
  return faceindex_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ClientCreateCharacter::faceindex() const {
  // @@protoc_insertion_point(field_get:Protocol.ClientCreateCharacter.faceIndex)
  return _internal_faceindex();
}
inline void ClientCreateCharacter::_internal_set_faceindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  faceindex_ = value;
}
inline void ClientCreateCharacter::set_faceindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_faceindex(value);
  // @@protoc_insertion_point(field_set:Protocol.ClientCreateCharacter.faceIndex)
}

// int32 shoesIndex = 6;
inline void ClientCreateCharacter::clear_shoesindex() {
  shoesindex_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ClientCreateCharacter::_internal_shoesindex() const {
  return shoesindex_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ClientCreateCharacter::shoesindex() const {
  // @@protoc_insertion_point(field_get:Protocol.ClientCreateCharacter.shoesIndex)
  return _internal_shoesindex();
}
inline void ClientCreateCharacter::_internal_set_shoesindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  shoesindex_ = value;
}
inline void ClientCreateCharacter::set_shoesindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_shoesindex(value);
  // @@protoc_insertion_point(field_set:Protocol.ClientCreateCharacter.shoesIndex)
}

// -------------------------------------------------------------------

// ServerCreateCharacter

// .Protocol.kCreateMessage result = 1;
inline void ServerCreateCharacter::clear_result() {
  result_ = 0;
}
inline ::Protocol::kCreateMessage ServerCreateCharacter::_internal_result() const {
  return static_cast< ::Protocol::kCreateMessage >(result_);
}
inline ::Protocol::kCreateMessage ServerCreateCharacter::result() const {
  // @@protoc_insertion_point(field_get:Protocol.ServerCreateCharacter.result)
  return _internal_result();
}
inline void ServerCreateCharacter::_internal_set_result(::Protocol::kCreateMessage value) {
  
  result_ = value;
}
inline void ServerCreateCharacter::set_result(::Protocol::kCreateMessage value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:Protocol.ServerCreateCharacter.result)
}

// .Protocol.ViewCharacter character = 2;
inline bool ServerCreateCharacter::_internal_has_character() const {
  return this != internal_default_instance() && character_ != nullptr;
}
inline bool ServerCreateCharacter::has_character() const {
  return _internal_has_character();
}
inline const ::Protocol::ViewCharacter& ServerCreateCharacter::_internal_character() const {
  const ::Protocol::ViewCharacter* p = character_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::ViewCharacter&>(
      ::Protocol::_ViewCharacter_default_instance_);
}
inline const ::Protocol::ViewCharacter& ServerCreateCharacter::character() const {
  // @@protoc_insertion_point(field_get:Protocol.ServerCreateCharacter.character)
  return _internal_character();
}
inline void ServerCreateCharacter::unsafe_arena_set_allocated_character(
    ::Protocol::ViewCharacter* character) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(character_);
  }
  character_ = character;
  if (character) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.ServerCreateCharacter.character)
}
inline ::Protocol::ViewCharacter* ServerCreateCharacter::release_character() {
  
  ::Protocol::ViewCharacter* temp = character_;
  character_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::ViewCharacter* ServerCreateCharacter::unsafe_arena_release_character() {
  // @@protoc_insertion_point(field_release:Protocol.ServerCreateCharacter.character)
  
  ::Protocol::ViewCharacter* temp = character_;
  character_ = nullptr;
  return temp;
}
inline ::Protocol::ViewCharacter* ServerCreateCharacter::_internal_mutable_character() {
  
  if (character_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::ViewCharacter>(GetArenaForAllocation());
    character_ = p;
  }
  return character_;
}
inline ::Protocol::ViewCharacter* ServerCreateCharacter::mutable_character() {
  // @@protoc_insertion_point(field_mutable:Protocol.ServerCreateCharacter.character)
  return _internal_mutable_character();
}
inline void ServerCreateCharacter::set_allocated_character(::Protocol::ViewCharacter* character) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(character_);
  }
  if (character) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(character));
    if (message_arena != submessage_arena) {
      character = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, character, submessage_arena);
    }
    
  } else {
    
  }
  character_ = character;
  // @@protoc_insertion_point(field_set_allocated:Protocol.ServerCreateCharacter.character)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2eproto
